openapi: 3.0.0
info:
  title: GenerateToken
  version: '1.0'
  description: Test Generate Token
  contact:
    name: Test
servers:
  - url: 'http://localhost:56492'
paths:
  /Auth/GenerateToken:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ResponseStatus:
                    type: boolean
                  ResponseData:
                    type: object
                    properties:
                      Token:
                        type: object
                        properties:
                          Token:
                            type: string
                          ExpiryTime:
                            type: string
                          ClientKey:
                            type: string
                  Message:
                    type: string
                  ErrorData:
                    type: string
      operationId: get-GenerateToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                UserName:
                  type: string
                  description: UserName Required
                Password:
                  type: string
                  description: Password Required.
              required:
                - UserName
                - Password
        description: ''
      description: Test Generate Token
    parameters: []
components:
  schemas: {}
